-- Execute no SQL Editor do Supabase.
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  materia text not null,
  assunto text,
  dificuldade integer check (dificuldade between 1 and 10),
  enunciado text not null,
  alternativas jsonb not null,
  correta integer not null check (correta between 0 and 4),
  justificativas jsonb not null,
  created_at timestamptz default now()
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  question_id bigint references public.questions(id) on delete cascade,
  selected_answer integer,
  correct boolean,
  elapsed_seconds integer default 0,
  created_at timestamptz default now()
);

alter table public.questions enable row level security;
alter table public.attempts enable row level security;

create policy "Questões públicas para leitura"
on public.questions for select
to anon, authenticated
using (true);

create policy "Usuário lê as próprias tentativas"
on public.attempts for select
to authenticated
using (auth.uid() = user_id);

create policy "Usuário registra as próprias tentativas"
on public.attempts for insert
to authenticated
with check (auth.uid() = user_id);
